# 应用服务 WEB 访问端口
server:
  port: 8333
# 应用名称
spring:
  application:
    name: small
  main:
    allow-bean-definition-overriding: true

  #数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/small?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root

#mybatis
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.small.small.dao

#日志
logging:
  level:
    root: info
  config: ./config/logback-spring.xml

